### ISSUE TITLE
Infinite loop spotted

### ISSUE THREAD

**Issue by haoqiang** [Cryrivers/SPA#15]
prog_line n1; stmt s,s2,s3; if ifstat; while w; variable v,v2; Select v such that Next (n1, s) and Parent (ifstat, s) and Modifies (w, v) and Uses (s, v) and Modifies(s2,v2) and Parent*(s2,s3) and Uses(s3, v2) with v.varName=v2.varName

By the this is ok, still testing....
prog_line n1; stmt s,s2,s3; if ifstat; while w; variable v,v2; Select v such that Next (n1, s) and Parent (ifstat, s) and Modifies (w, v) and Uses (s, v) and Modifies(s2,v2) and Parent*(s2,s3) and Uses(s3, v2)

**Comment by Cryrivers** [comment]
**Query:**
prog_line n1; stmt s,s2,s3; if ifstat; while w; variable v,v2; Select v such that Next (n1, s) and Parent (ifs
tat, s) and Modifies (w, v) and Uses (s, v) and Modifies(s2,v2) and Parent*(s2,s3) and Uses(s3, v2)

**Processor: 26876 milliseconds.**

**Result:**
back; blue; cold; com; dear; dell; eat; engin; fass; fat; front; green; idea; indigo; left; never; orange; pit
; plain; pure; ratio; red; right; salt; science; sde; slim; soc; temp; top; violet; warm; yellow;

Any solution to reducing the processing time?

**Comment by Cryrivers** [comment]
As for the infinite loop. I guess it is @zhenming 's issue.

when I break the program, it stops at here:

![image](https://f.cloud.github.com/assets/1313238/213388/05c90c30-837e-11e2-8adb-15329e06f3b7.png)

Ignore the `std::` thing in call stack, the program seems to be stuck at `QueryEvaluator::intersectDependencyMapPair`

**Comment by zhenming** [comment]
I ran on CS3202Test1Code.c, and it worked fine, which program you guys run on?

anyway haoqiang, there is some error in the dependency you gave me

for n1, ifstat and w, you gave me dependency 7, should be -1.

**Comment by zhenming** [comment]
ok i realise its test2code.c, does the program terminate? or it just takes very long? 

mine seem to hang at the last query clause "Uses(s3, v2)". it works for a smaller program, but hangs for a larger one, so i think the problem should be due to the size.

I will give you guys an idea, there are currently 7 or 8 dependent variables (7 if there is no merge). If hq give me the correct dependency, there will be 4 or 5 dependent variables.

if we have an average of 100 values per variable, then there will be about 100^8 values stored by the QE due to cartesian product which is about 10,000,000,000,000,000 values. Of course it will take a long time. 

if it is 100^5, it is 10,000,000,000 which is a big difference. 

Furthermore, there is no query optimisation yet, I will try to look into the problem, but there is always a limit to how much the query evaluator can handle. e.g. if we have 100 dependent query variables then the size will be 100^100 which is crazy.

**Comment by haoqiang** [comment]
prog_line n1; stmt s,s2,s3; if ifstat; while w; variable v,v2; Select v such that Next (n1, s) and Parent (ifstat, s) and Modifies (w, v) and Uses (s, v) and Modifies(s2,v2) and Parent*(s2,s3) and Uses(s3, v2)  This one is quite good

Should there be such a different to add three more dependency? 

And since the dependency are all the same, shouldn't the result become smaller and smaller?
